/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pets;

import Business.Pets.Pet;
import Business.Pets.PetDirectory;
import Business.Pets.ScheduleVitalSign;
import Business.Validator.Validator;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Timer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neha Ghate
 */
public class AddPetsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPetsJPanel
     */
    JPanel container;
    PetDirectory petDirectory;
    Pet pet;

    public AddPetsJPanel(JPanel container, PetDirectory petDirectory) {
        initComponents();
        this.container = container;
        this.petDirectory = petDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petNamejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addDonorjButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        petBreedjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uploadJButton = new javax.swing.JButton();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        jToggleButton = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        petNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Pet's  Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Pet Name");

        addDonorjButton.setText("Add Pet");
        addDonorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorjButtonActionPerformed(evt);
            }
        });

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Pet DOB:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Pet Breed:");

        uploadJButton.setText("Upload an Image");
        uploadJButton.setEnabled(false);
        uploadJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadJButtonActionPerformed(evt);
            }
        });

        dobDateChooser.setMaxSelectableDate(new Date());

        jToggleButton.setText("Start the sensor");
        jToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(petNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(347, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(petBreedjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jToggleButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(addDonorjButton)
                                .addGap(83, 83, 83)
                                .addComponent(uploadJButton)))
                        .addGap(0, 218, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(dobDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(petBreedjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(223, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDonorjButton)
                            .addComponent(uploadJButton))
                        .addGap(183, 183, 183)))
                .addComponent(backjButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDonorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorjButtonActionPerformed
        // TODO add your handling code here:
        String petName = petNamejTextField.getText();
        String petBreed = petBreedjTextField.getText();
        Timer time = new Timer();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //Date date = new Date();
        Date dob = dobDateChooser.getDate();
        pet = new Pet();
        ArrayList<String> errorArray = new ArrayList();
       // System.out.println(dob);

        if (Validator.isStringValid(petName)) {
            pet.setPetName(petName);
        } else {
            errorArray.add("Pet Name");

        }
        if (Validator.isStringValid(petBreed)) {
            pet.setPetBreed(petBreed);
        } else {
            errorArray.add("Breed Name");

        }
        if (dob != null) {
            pet.setDob(dob);
        } else {
            errorArray.add("Date of birth");
        }

        if (!errorArray.isEmpty()) {

            String message = "";
            //Iterate the errorListArray with foreach
            for (String error : errorArray) {
                message += error + " \n";
            }
            JOptionPane.showMessageDialog(null, message + "are empty fields. Please enter the values.", "Error ", JOptionPane.ERROR_MESSAGE);
        } else {
            pet = petDirectory.createPet(pet);

            System.out.println(dob);
            JOptionPane.showMessageDialog(null, "Pet is added", "Pet Addition", JOptionPane.INFORMATION_MESSAGE);
            addDonorjButton.setEnabled(false);
            uploadJButton.setEnabled(true);
            if (jToggleButton.isSelected()) {
                ScheduleVitalSign st = new ScheduleVitalSign(pet); // Instantiate SheduledTask class
                time.schedule(st, new Date(), 10000); // Create Repetitively task for every 10 secs
            }

        }

    }//GEN-LAST:event_addDonorjButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void uploadJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadJButtonActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ImageUploadJFrame", new ImageUpload(container, pet));
        layout.next(container);
    }//GEN-LAST:event_uploadJButtonActionPerformed

    private void petNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petNamejTextFieldActionPerformed

    private void jToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDonorjButton;
    private javax.swing.JButton backjButton1;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton;
    private javax.swing.JTextField petBreedjTextField;
    private javax.swing.JTextField petNamejTextField;
    private javax.swing.JButton uploadJButton;
    // End of variables declaration//GEN-END:variables
}
