/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pets;

import Business.Pets.Pet;
import Business.Pets.PetDirectory;
import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neha Ghate
 */
public class ImageUpload extends javax.swing.JPanel {

    /**
     * Creates new form ImageUpload
     */
    private JPanel userProcessContainer;
    Pet pet;
    public ImageUpload(JPanel userProcessContainer,Pet pet) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pet = pet;
    }
    private static final int IMG_WIDTH = 100;
    private static final int IMG_HEIGHT = 100;
       
    
     private static BufferedImage resizeImage(BufferedImage originalImage, int type){
	BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
	Graphics2D g = resizedImage.createGraphics();
	g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
	g.dispose();
		
	return resizedImage;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petImageJLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        attachImageButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        petImageJLabel.setText("Pet Image");

        jTextField1.setText("jTextField1");

        attachImageButton.setText("Attach");
        attachImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachImageButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(attachImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(petImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(petImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attachImageButton))
                .addGap(29, 29, 29)
                .addComponent(backJButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void attachImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachImageButtonActionPerformed
        // TODO add your handling code here:

        JFileChooser filechooser= new JFileChooser();
        filechooser.setDialogTitle("Choose Your File");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //below codes for select  the file

        int returnval=filechooser.showOpenDialog(this);
        if(returnval==JFileChooser.APPROVE_OPTION)
        {
            File file = filechooser.getSelectedFile();
            BufferedImage bi;
            
            try
            {   //display the image in jlabel

                String fileName = file.getAbsolutePath();
                jTextField1.setText(fileName);
                BufferedImage originalImage = ImageIO.read(file);
                if(originalImage == null){
                      JOptionPane.showMessageDialog(null, "Select an image file","Image file",JOptionPane.WARNING_MESSAGE);       
                }
                else{
                int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

                BufferedImage resizeImageJpg = resizeImage(originalImage, type);
                ImageIO.write(resizeImageJpg, "jpg", new File(fileName));

                bi=ImageIO.read(file);
                petImageJLabel.setIcon(new ImageIcon(bi));
                pet.setPetImage(resizeImageJpg);
                }
            }
            catch(IOException e)
            {
                 JOptionPane.showMessageDialog(null, "Select an image file","Image file",JOptionPane.WARNING_MESSAGE);       
            }
          //  this.pack();
        }
    }//GEN-LAST:event_attachImageButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachImageButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel petImageJLabel;
    // End of variables declaration//GEN-END:variables
}
