/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProcessingJPanel;

import Business.SendSMS;
import Business.Validator.Validator;
import Business.WorkQueue.PetGiverWorkRequest;
import Business.WriteToFile;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.time.Year;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import userinterface.PetAdoptionRoles.PetGiverWorkAreaJPanel;

/**
 *
 * @author Neha Ghate
 */
public class PetGiverProcessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetGiverProcessJPanel
     */
    private JPanel userProcessContainer;
    private PetGiverWorkRequest request;

    public PetGiverProcessJPanel(JPanel userProcessContainer, PetGiverWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        showDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void showDetails() {
        petDobJText.setText((String.valueOf(request.getPet().getDob())));
        petNameJText.setText(request.getPet().getPetName());
        petBreedJText.setText(request.getPet().getPetBreed());
        messageJLabel.setText(request.getMessage());
        Date dob = request.getPet().getDob();
        LocalDate start = dob.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate end = LocalDate.now(); // use for age-calculation: LocalDate.now()
        long years = ChronoUnit.YEARS.between(start, end);
        ageJText.setText(Long.toString(years));
        tenureJLabel.setText(request.getTenure());
        if(request.getTenure().equals("Forever")){
        daysJLabel.setText("Not Applicable");
        startDateJLabel.setText("Not Applicable");
        }
        else{
            daysJLabel.setText((Integer.toString(request.getNumberOfDays())));
        startDateJLabel.setText((String.valueOf(request.getStartDate())));
        }
        // BufferedImage bi = request.getPet().getPetImage();
        // petImageJLabel.setIcon(new ImageIcon(bi));
    }
   

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultJTextField = new javax.swing.JTextArea();
        petDobJText = new javax.swing.JLabel();
        petBreedJText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        petImageJLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        petNameJText = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ageJText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageJLabel = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        startDateJLabel = new javax.swing.JLabel();
        tenureJLabel = new javax.swing.JLabel();
        ageJText2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        daysJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        setForeground(new java.awt.Color(0, 102, 102));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Message for acceptance:");

        jLabel2.setText("Pet Giver Work Area");

        resultJTextField.setColumns(20);
        resultJTextField.setRows(5);
        jScrollPane1.setViewportView(resultJTextField);

        petDobJText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        petDobJText.setForeground(new java.awt.Color(0, 102, 102));
        petDobJText.setText("Pet DOB");

        petBreedJText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        petBreedJText.setForeground(new java.awt.Color(0, 102, 102));
        petBreedJText.setText("Pet Breed");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Tenure :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Pet DOB:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Pet Breed:");

        petNameJText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        petNameJText.setForeground(new java.awt.Color(0, 102, 102));
        petNameJText.setText("Pet Name");

        jButton1.setText("Show Location");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Message:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Age:");

        ageJText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        ageJText.setForeground(new java.awt.Color(0, 102, 102));
        ageJText.setText("jLabel7");

        messageJLabel.setEditable(false);
        messageJLabel.setColumns(20);
        messageJLabel.setRows(5);
        jScrollPane2.setViewportView(messageJLabel);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Pet Name:");

        startDateJLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        startDateJLabel.setForeground(new java.awt.Color(0, 102, 102));
        startDateJLabel.setText("date");

        tenureJLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        tenureJLabel.setForeground(new java.awt.Color(0, 102, 102));
        tenureJLabel.setText("jLabel7");

        ageJText2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        ageJText2.setForeground(new java.awt.Color(0, 102, 102));
        ageJText2.setText("Start Date:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Number of days:");

        daysJLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        daysJLabel.setForeground(new java.awt.Color(0, 102, 102));
        daysJLabel.setText("days");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("days");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageJText, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(petNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(petBreedJText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ageJText2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(startDateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tenureJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(petDobJText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(petImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(daysJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton1))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(backJButton)
                        .addGap(114, 114, 114)
                        .addComponent(submitJButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(petImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(petNameJText)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4)
                                            .addComponent(petDobJText))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ageJText)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel3)
                                            .addComponent(tenureJLabel))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(startDateJLabel)
                                            .addComponent(ageJText2)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(petBreedJText)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(daysJLabel)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(backJButton)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitJButton)
                        .addGap(45, 45, 45))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PetGiverWorkAreaJPanel dwjp = (PetGiverWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        String name = resultJTextField.getText();
        if (Validator.isStringValid(name)) {
            request.setTestResult(name);
            request.setStatus("Completed");
            request.setResolveDate(new Date());
            WriteToFile.getData(request.getReceiver() + " accepted the request on " + new Date());
            JOptionPane.showMessageDialog(null, "Result  is added", "Result Addition", JOptionPane.INFORMATION_MESSAGE);
            SendSMS.sendNotificationMessage(request.getSender(), request);
        } else {
            JOptionPane.showMessageDialog(null, "Test result cannot be empty", "Empty file", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Browser browser = new Browser();
        BrowserView browserView = new BrowserView(browser);

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        frame.add(browserView, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setTitle("Pet Location");
        //browser.loadURL("C://My Work//AED//direction.html");
        //browser.loadURL(".//map.html");
        browser.loadHTML("<!DocType>\n" +
"<html>\n" +
"  <head>\n" +
" <title>Location Direction</title>\n" +
"      <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\" />\n" +
"    <style type=\"text/css\">\n" +
"      html { height: 100% }\n" +
"      body { height: 100%; margin: 0; padding: 0 }\n" +
"      #map-canvas { height: 100% }\n" +
"    </style>\n" +
"    <script type=\"text/javascript\"\n" +
"      src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyB7J1zsErb9_7jxNu5KU5kIENFObAQEbl0&sensor=false\">\n" +
"    </script>\n" +
"    <script type=\"text/javascript\">\n" +
"     \n" +
"      function initialize() {\n" +
"       var chicago = {lat: 42.3529, lng: -71.1321};\n" +
"  var indianapolis = {lat: 42.3389, lng:  -71.098326};\n" +
"\n" +
"  var map = new google.maps.Map(document.getElementById('map-canvas'), {\n" +
"    center: chicago,\n" +
"    scrollwheel: false,\n" +
"    zoom: 14\n" +
"  });\n" +
"\n" +
"  var directionsDisplay = new google.maps.DirectionsRenderer({\n" +
"    map: map\n" +
"  });\n" +
"\n" +
"  // Set destination, origin and travel mode.\n" +
"  var request = {\n" +
"    destination: indianapolis,\n" +
"    origin: chicago,\n" +
"    travelMode: google.maps.TravelMode.DRIVING\n" +
"  };\n" +
"\n" +
"  // Pass the directions request to the directions service.\n" +
"  var directionsService = new google.maps.DirectionsService();\n" +
"  directionsService.route(request, function(response, status) {\n" +
"    if (status == google.maps.DirectionsStatus.OK) {\n" +
"      // Display the route on the map.\n" +
"      directionsDisplay.setDirections(response);\n" +
"    }\n" +
"  });\n" +
"  \n" +
"   \n" +
"  }\n" +
"	 \n" +
"       google.maps.event.addDomListener(window, 'load', initialize);\n" +
"	  \n" +
"    </script>\n" +
"  </head>\n" +
"  <body>\n" +
"    <div id=\"map-canvas\"/>\n" +
"  </body>\n" +
"</html>");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageJText;
    private javax.swing.JLabel ageJText2;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel daysJLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageJLabel;
    private javax.swing.JLabel petBreedJText;
    private javax.swing.JLabel petDobJText;
    private javax.swing.JLabel petImageJLabel;
    private javax.swing.JLabel petNameJText;
    private javax.swing.JTextArea resultJTextField;
    private javax.swing.JLabel startDateJLabel;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel tenureJLabel;
    // End of variables declaration//GEN-END:variables
}
