/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProcessingJPanel;

import Business.SendSMS;
import Business.Validator.Validator;
import Business.WorkQueue.PetWalkerWorkRequest;
import Business.WriteToFile;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import userinterface.PetAdoptionRoles.PetWalkerWorkAreaJPanel;

/**
 *
 * @author Neha Ghate
 */
public class PetWalkerProcessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetGiverProcessJPanel
     */
     JPanel userProcessContainer;
    PetWalkerWorkRequest request;
    public PetWalkerProcessJPanel( JPanel userProcessContainer,PetWalkerWorkRequest request) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.request = request;
        showDetails();
    }

    private void showDetails(){
        senderJLabel.setText(request.getSender().getEmployee().getName());
        dateJLabel.setText((String.valueOf(request.getDateOfWalkRequest())));
        hoursjLabel.setText((Integer.toString(request.getNumberOfHours())));
        petNameJLabel.setText(request.getPet().getPetName());
        messageJLabel.setText(request.getMessage());
         Date dob = request.getPet().getDob();
        LocalDate start = dob.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate end = LocalDate.now(); // use for age-calculation: LocalDate.now()
        long years = ChronoUnit.YEARS.between(start, end);
        ageJText.setText(Long.toString(years));
      //  BufferedImage bi = request.getPet().getPetImage();
      //  petImageLabel.setIcon(new ImageIcon(bi));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senderJLabel = new javax.swing.JLabel();
        dateJLabel = new javax.swing.JLabel();
        hoursjLabel = new javax.swing.JLabel();
        petNameJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultJTextField = new javax.swing.JTextArea();
        directionJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ageJText = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageJLabel = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Result");

        jLabel2.setText("Pet Walker Work Area");

        senderJLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        senderJLabel.setForeground(new java.awt.Color(0, 102, 102));
        senderJLabel.setText("jLabel3");

        dateJLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        dateJLabel.setForeground(new java.awt.Color(0, 102, 102));
        dateJLabel.setText("jLabel3");

        hoursjLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        hoursjLabel.setForeground(new java.awt.Color(0, 102, 102));
        hoursjLabel.setText("jLabel3");

        petNameJLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        petNameJLabel.setForeground(new java.awt.Color(0, 102, 102));
        petNameJLabel.setText("jLabel3");

        resultJTextField.setColumns(20);
        resultJTextField.setRows(5);
        jScrollPane1.setViewportView(resultJTextField);

        directionJButton.setText("Show Directions");
        directionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directionJButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Date Time of Walking:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Number of hours:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Owner Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Pet Name:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Message:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Age:");

        ageJText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        ageJText.setForeground(new java.awt.Color(0, 102, 102));
        ageJText.setText("jLabel7");

        messageJLabel.setEditable(false);
        messageJLabel.setColumns(20);
        messageJLabel.setRows(5);
        jScrollPane3.setViewportView(messageJLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(senderJLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ageJText)
                                        .addComponent(hoursjLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(backJButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(petNameJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(submitJButton)))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(directionJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senderJLabel)
                    .addComponent(petNameJLabel)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateJLabel)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hoursjLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ageJText))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(directionJButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backJButton)
                            .addComponent(submitJButton))
                        .addGap(58, 58, 58))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PetWalkerWorkAreaJPanel dwjp = (PetWalkerWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        String name = resultJTextField.getText(); 
       
        if(Validator.isStringValid(name)){
             request.setTestResult(name);
            request.setStatus("Completed");
        request.setResolveDate(new Date());
          WriteToFile.getData(request.getReceiver()+" accepted the request on "+new Date());
        JOptionPane.showMessageDialog(null, "Result  is added","Result Addition",JOptionPane.INFORMATION_MESSAGE);
        SendSMS.sendNotificationMessage(request.getSender(), request);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Test result cannot be empty","Empty text field",JOptionPane.WARNING_MESSAGE);       
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void directionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionJButtonActionPerformed
        // TODO add your handling code here:
         Browser browser = new Browser();
        BrowserView browserView = new BrowserView(browser);

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        frame.add(browserView, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setTitle("Pet Location");
       // browser.loadURL("C://My Work//AED//direction.html");
        browser.loadHTML("<!DocType>\n" +
"<html>\n" +
"  <head>\n" +
" <title>Location Direction</title>\n" +
"      <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\" />\n" +
"    <style type=\"text/css\">\n" +
"      html { height: 100% }\n" +
"      body { height: 100%; margin: 0; padding: 0 }\n" +
"      #map-canvas { height: 100% }\n" +
"    </style>\n" +
"    <script type=\"text/javascript\"\n" +
"      src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyB7J1zsErb9_7jxNu5KU5kIENFObAQEbl0&sensor=false\">\n" +
"    </script>\n" +
"    <script type=\"text/javascript\">\n" +
"     \n" +
"      function initialize() {\n" +
"       var chicago = {lat: 42.3529, lng: -71.1321};\n" +
"  var indianapolis = {lat: 42.3389, lng:  -71.098326};\n" +
"\n" +
"  var map = new google.maps.Map(document.getElementById('map-canvas'), {\n" +
"    center: chicago,\n" +
"    scrollwheel: false,\n" +
"    zoom: 14\n" +
"  });\n" +
"\n" +
"  var directionsDisplay = new google.maps.DirectionsRenderer({\n" +
"    map: map\n" +
"  });\n" +
"\n" +
"  // Set destination, origin and travel mode.\n" +
"  var request = {\n" +
"    destination: indianapolis,\n" +
"    origin: chicago,\n" +
"    travelMode: google.maps.TravelMode.DRIVING\n" +
"  };\n" +
"\n" +
"  // Pass the directions request to the directions service.\n" +
"  var directionsService = new google.maps.DirectionsService();\n" +
"  directionsService.route(request, function(response, status) {\n" +
"    if (status == google.maps.DirectionsStatus.OK) {\n" +
"      // Display the route on the map.\n" +
"      directionsDisplay.setDirections(response);\n" +
"    }\n" +
"  });\n" +
"  \n" +
"   \n" +
"  }\n" +
"	 \n" +
"       google.maps.event.addDomListener(window, 'load', initialize);\n" +
"	  \n" +
"    </script>\n" +
"  </head>\n" +
"  <body>\n" +
"    <div id=\"map-canvas\"/>\n" +
"  </body>\n" +
"</html>");
    }//GEN-LAST:event_directionJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageJText;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel dateJLabel;
    private javax.swing.JButton directionJButton;
    private javax.swing.JLabel hoursjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messageJLabel;
    private javax.swing.JLabel petNameJLabel;
    private javax.swing.JTextArea resultJTextField;
    private javax.swing.JLabel senderJLabel;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
